class Images {
  Images._();

  static const logo = 'assets/logo.png';
  static const icError = 'assets/ic_error.png';
  static const icDown = 'assets/ic_down.png';
  static const icHistoryActive = 'assets/ic_history_active.png';
  static const icHomeActive = 'assets/ic_home_active.png';
  static const icAccountActive = 'assets/ic_account_active.png';
  static const icCashierActive = 'assets/ic_cashier_active.png';
  static const bgHome = 'assets/bg_home.png';
  static const icServiceList = 'assets/ic_service_list.png';
  static const icStore = 'assets/ic_store.png';
  static const icUserList = 'assets/ic_user_list.png';
  static const icPerson = 'assets/ic_person.png';
  static const icCommission = 'assets/ic_commission.png';
  static const icRevenue = 'assets/ic_revenue.png';
  static const icBooking = 'assets/ic_booking.png';
  static const icProduct = 'assets/ic_product.png';
  static const icNotification = 'assets/ic_notification.png';
  static const icAccAboutApp = 'assets/ic_acc_about_app.png';
  static const icAccGuide = 'assets/ic_acc_guide.png';
  static const icAccLogout = 'assets/ic_acc_logout.png';
  static const icAccNotify = 'assets/ic_acc_notify.png';
  static const icAccOrderlist = 'assets/ic_acc_orderlist.png';
  static const icRight = 'assets/ic_right.png';
  static const icClose = 'assets/ic_close.png';
  static const icCamera = 'assets/ic_camera.png';
  static const icBag = 'assets/ic_bag.png';
  static const icSearch = 'assets/ic_search.png';
  static const icMessage = 'assets/ic_message.png';
  static const icSearchActive = 'assets/ic_search_active.png';
  static const icCash = 'assets/ic_cash.png';
  static const icCard = 'assets/ic_card.png';
  static const icMomo = 'assets/ic_momo.png';
  static const icPhone = 'assets/ic_phone.png';
  static const icAddress = 'assets/ic_address.png';
  static const icEdit = 'assets/ic_edit.png';
  static const icArrowBack = 'assets/ic_arrow_back.png';
}
