class Strings {
  static final String ten = 'Tên';
  static final String tenHint = 'Vd. Nguyễn';
  static final String ho = 'Họ';
  static final String hoHint = 'Vd. Như';
  static final String quocGia = 'Quốc gia';
  static final String quocGiaHint = 'Chọn quốc gia trong danh sách';
  static final String email = 'Email';
  static final String emailHint = 'Nhập địa chỉ email';
  static final String khoiPhucMatKhau = 'Khôi phục mật khẩu';
  static final String appName = 'KayLee';
  static final String chuaCoTK = 'Chưa có tài khoản?';
  static final String login = 'Login';
  static final String dangKy = 'Đăng ký';
  static final String vuiLongDangNhap = 'Vui lòng đăng nhập để tiếp tục';
  static final String dangNhap = 'Đăng nhập';
  static final String soDienThoai = 'Số điện thoại';
  static final String phoneLimitHint = 'Tối thiểu 9 số không dấu cách';
  static final String passLimitHint = 'Tối thiểu 8 ký tự gồm chữ và số';
  static final String matKhau = 'Mật khẩu';
  static final String quenMatKhau = 'Quên mật khẩu';
  static final String khoiTaoTaiKhoan = 'Khởi tạo tài khoản';
  static final String dieuKhoanVaDieuKien = 'Điều khoản và điều kiện';
  static final String policyContent =
      'Mauris tristique enim elementum, rhoncus lorem nec, finibus ipsum. Integer iaculis, neque non varius mollis, neque quam finibus enim, non mattis dolor dui eu urna. In scelerisque magna eu euismod rutrum. Sed sit amet nisi a lorem accumsan porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent gravida blandit mi non tempor. Cras sed nisl porta purus pharetra hendrerit interdum at neque.'
      'Maecenas at tortor ultricies, lacinia dui quis, elementum dolor. In sodales efficitur quam, sed scelerisque felis sodales eu. Proin pulvinar sem eu euismod maximus. Donec eros turpis, euismod non neque ut, auctor porttitor ante. Vivamus volutpat lacus sed nibh ullamcorper facilisis. Praesent feugiat egestas finibus. Quisque ipsum nisi, lobortis vel vehicula vel, accumsan nec tellus.'
      'Proin ac nisi id mauris blandit posuere a sit amet dolor. Quisque vulputate vitae eros ut tincidunt. Integer egestas egestas nibh eu mattis. Donec et aliquet erat. Sed id commodo orci, vel fermentum nunc. Donec quis vehicula elit, quis hendrerit purus. Proin ut mi ac quam rhoncus dignissim a sed sem. Donec vitae tellus a ex aliquet vulputate mollis quis nisi.'
      'Proin pulvinar sem eu euismod maximus. Donec eros turpis, euismod non neque ut, auctor porttitor ante. Vivamus volutpat lacus sed nibh ullamcorper facilisis.';
  static final String xacNhanOtp = 'Xác nhận OTP';
  static final String guiOtp = 'Gửi OTP';
  static final String lienHeChungToi = 'Liên hệ với chúng tôi';
  static final String vuiLongNhapOtpHint =
      'Vui lòng nhập mã OTP được gửi đến số điện thoại của bạn';
  static final String nhapOtp = 'Nhập OTP';
  static final String khongNhanDcSms = 'Không nhận được tin nhắn?';
  static final String guiLai = 'Gửi lại';
  static final String trangChu = 'Trang chủ';
  static final String thuNgan = 'Thu ngân';
  static final String lichSuDh = 'Lịch sử ĐH';
  static final String taiKhoan = 'Tài khoản';
  static final String dsNhaCc = 'Danh sách nhà cung cấp';
  static final String qlChiNhanh = 'Quản lý\nchi nhánh';
  static final String dsDichVu = 'Danh sách\ndịch vụ';
  static final String dsSanPham = 'Danh sách\nsản phẩm';
  static final String qlNhanVien = 'Quản lý\nnhân viên';
  static final String dsKhachHang = 'Danh sách\nkhách hàng';
  static final String dsLichHen = 'Danh sách\nlịch hẹn';
  static final String hoaHongNv = 'Hoa hồng\nnhân viên';
  static final String doanhThuBanHang = 'Doanh thu\nbán hàng';
  static final String timDonHangHint = 'Tìm đơn hàng';
  static final String chonLoc = 'Chọn lọc';
  static final String chiTietDH = 'CHI TIẾT ĐƠN HÀNG';
  static final String thongTinKh = 'Thông tin khách hàng';
  static final String chiNhanh = 'Chi nhánh';
  static final String suThongTin = 'Sửa thông tin';
  static final String thongBao = 'Thông báo';
  static final String huongDanSd = 'Hướng dẫn sử dụng';
  static final String thongTinUngDung = 'Thông tin về ứng dụng';
  static final String quanlyDonDh = 'Quản lý đơn đặt hàng';
  static final String dangXuat = 'Đăng xuất';
  static final String xoaTatCa = 'Xoá tất cả';
  static final String timThongBaoTheoTuKhoa = 'Tìm thông báo theo từ khoá';
  static final String xoa = 'Xoá';
  static final String chinhSuThongTinCaNhan = 'Chỉnh sửa thông tin cá nhân';
  static final String luu = 'Lưu';
  static final String diaChiHienTai = 'Địa chỉ hiện tại';
  static final String diaChiHienTaiHint = 'Số nhà, tên cư xá hoặc khu dân cư';
  static final String namSinh = 'Năm sinh';
  static final String queQuan = 'Quê quán';
  static final String chonTinhTpHint = 'Chọn Tỉnh/Thành phố';
  static final String phuong = 'Phường';
  static final String quan = 'Quận';
  static final String doiMatKhau = 'Đổi mật khẩu';
  static final String chinhSuaHinhDaiDien = 'Chỉnh sửa hình đại diện';
  static final String danhMucDichVu = 'Danh mục dịch vụ';
  static final String dsNhanVien = 'Danh sách nhân viên';
  static final String danhSachKH = 'Danh sách khách hàng';
  static final String chiTietSanPham = 'Chi tiết sản phẩm';
  static final String themVaoGioHang = 'Thêm vào giỏ hàng';
  static final String gioHang = 'Giỏ hàng';
  static final String datHang = 'Đặt hàng';
  static final String thongTinNguoiNhan = 'Thông tin người nhận';
  static final String tiepTuc = 'Tiếp tục';
  static final String luuY = 'Lưu ý';
  static final String luuYHint = 'Nhập ghi chú cho đơn hàng';
  static final String nhapMatKhauMoi = 'Nhập mật khẩu mới';
  static final String matKhauMoi = 'Mật khẩu mới';
  static final String xacNhan = 'Xác nhận';

  Strings._();
}
