require 'dotenv'

default_platform(:ios)
platform :ios do
  desc "Build an ipa"

  before_all do
    Dir.chdir('../..') do
        Dotenv.load('.env')
        sh('flutter', 'clean')
        sh('flutter', 'packages', 'get')
    end
  end

  lane :dev do
    Dir.chdir('../..') do
        Dotenv.load('.env.dev')
        sh('flutter', 'build', 'ios', '--flavor', ENV['FLAVOR'], '--target', ENV['TARGET'])
    end
    build_ios_app(
        scheme: ENV['FLAVOR'],
        clean: true,
        output_directory: ENV['OUTPUT_DIRECTORY'],
        xcargs: "-allowProvisioningUpdates",
        export_method: "development"
    )
    firebase_app_distribution(
       app: ENV['FIREBASE_IOS_APP_ID'],
       firebase_cli_token: ENV['PRIVATE_FIREBASE_CLI_TOKEN'],
       ipa_path: ENV['IPA_PATH'],
       testers_file: ENV['TESTERS_FILE'],
       groups_file: ENV['GROUPS_FILE'],
       release_notes_file: ENV['RELEASE_NOTES_FILE']
    )
  end

  lane :prod do
    Dir.chdir('../..') do
        Dotenv.load('.env.prod')
        sh('flutter', 'build', 'ios', '--flavor', ENV['FLAVOR'], '--target', ENV['TARGET'])
        build_ios_app(
            scheme: ENV['FLAVOR'],
            clean: true,
            output_directory: ENV['OUTPUT_DIRECTORY'],
            xcargs: "-allowProvisioningUpdates",
            export_method: "app-store"
        )
    end
  end
end