name: core_plugin
description: A new Flutter package.
version: 1.0.22
homepage: https://tungpt.com
publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  url_launcher: ^6.0.20

  # dio, http request
  dio_http: ^5.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1+1

  logger: ^1.1.0
  equatable: ^2.0.3

  # bloc, state management
  flutter_bloc: ^8.0.1

  rxdart: ^0.27.3

  # json serializable
  json_annotation: ^4.4.0

  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.4

  path_provider: ^2.0.9
  toast:
    git:
      url: https://github.com/appdev/FlutterToast.git
      ref: master
  flutter_local_notifications: ^9.4.0
  firebase_messaging: ^11.2.12
  cached_network_image: ^3.2.0
  store_redirect: ^2.0.1
  package_info: ^2.0.2
  share: ^2.0.4
  flutter_widget_from_html: ^0.8.5
  flutter_cache_manager: ^3.3.0
  firebase_core: ^1.14.0
  get_it: ^7.2.0
  unfocus_widget: ^0.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/error.png
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
