name: anth_package
description: A new Flutter module.
version: 1.0.21
homepage: https://tungpt.com
publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.7.5
  core_plugin:
    path: ../flutter.core_plugin
#    git:
#      url: https://github.com/tungpham6195/flutter.core_plugin.git
#      ref: 1.0.22
  syncfusion_flutter_sliders: ^19.4.56
  image_picker: ^0.8.4+11
  extended_masked_text: ^2.3.1
  esc_pos_printer: ^4.1.0
  video_player: ^2.3.0
  chewie: ^1.3.1
  app_settings: ^4.1.1
  firebase_remote_config: ^2.0.3
  permission_handler: ^9.2.0
  injectable: ^1.5.3
  flutter_native_splash: ^2.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - receipt_fonts/
    - icons/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
