default_platform(:android)
platform :android do
  desc "build apk/app_bundle"
  lane :dev do
    Dir.chdir("../..") do
      sh "flutter packages get"
      sh "flutter clean"
      sh "flutter build apk --flavor=dev --target=lib/main_dev.dart --no-shrink"
    end
  end

  lane :prod do
      Dir.chdir("../..") do
        sh "flutter packages get"
        sh "flutter clean"
        sh "flutter build appbundle --flavor=prod --no-shrink"
      end
    end
end