require 'dotenv'
import('../../GeneralFastfile')

default_platform(:android)
platform :android do
  desc "build apk/aab"

  before_all do
    update_gem
    flutter_build
  end

  lane :dev do
    uploading_firebase_distribution
  end

  lane :prod do
    upload_store
  end
end